project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('quality_control/', include('quality_control.urls')),
    path('tasks/', include('tasks.urls')),
]

project_tracker/quality_control/urls.py
from django.urls import path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    #path('', views.index),
    path('bugs/', views.bug_list, name='bugs_list'),
    path('features/', views.feature_list, name='feature_list'),
    #path('bugs/<int:bug_id>/', views.bug_detail, name='bugs_detail'),
    #path('features/<int:feature_id>/', views.feature_id_detail, name='feature_id_detail'),

    path('', views.IndexView.as_view(), name='index'),
    path('bugs/<int:bug_id>/', views.BugsDetailView.as_view(), name='bugs_detail'),
    path('bugs/new/', views.create_bugreport, name='create_bugreport'),
    path('features/new/', views.create_featurerequest, name='create_featurerequest'),
    path('features/<int:feature_id>/', views.FeaturesDetailView.as_view(), name='feature_detail'),
    path('bugs/create/', views.BugReportCreateView.as_view(), name='create_bugreport'),
    path('features/create/', views.FeatureRequestCreateView.as_view(), name='create_featurerequest'),
    path('bugs/<int:bug_id>/update/', views.update_bugreport, name='update_bugreport'),
    path('features/<int:feature_id>/update/', views.update_featurerequest, name='update_featurerequest'),
    path('bugs/<int:bug_id>/update/', views.BugReportUpdateView.as_view(), name='update_bugreport'),
    path('features/<int:feature_id>/update/', views.FeatureRequestUpdateView.as_view(), name='update_featurerequest'),
    path('bugs/<int:bug_id>/delete/', views.delete_bug, name='delete_bug'),
    path('features/<int:feature_id>/delete/', views.delete_feature, name='delete_feature'),
]

project_tracker/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [

    # path('', views.index),
    # path('projects/', views.projects_list, name='projects_list'),
    # path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    
    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('project/new/', views.create_project, name='create_project'),
    path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),
    path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    path('project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
]

project_tracker/quality_control/models.py
from django.db import models
from tasks.models import Project, Task


class BugReport(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(Task, on_delete=models.SET_NULL, null=True)
    STATUS_CHOICES = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена'),
    ]
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New',
    )
    priority = models.IntegerField((1, 2, 3, 4, 5))
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


class FeatureRequest(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(Task, on_delete=models.SET_NULL, null=True)
    STATUS_CHOICES = [('Consideration', "Рассмотрение"),
                      ('Accepted', "Принято"),
                      ('Rejected', "Отклонено")]
    status = models.CharField(
        max_length=100,
        choices=STATUS_CHOICES,
        default="Рассмотрение"
    )
    priority = models.IntegerField((1, 2, 3, 4, 5))
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

project_tracker/quality_control/forms.py
from django import forms
from django.forms import ModelForm
from .models import BugReport, FeatureRequest


class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']


class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

project_tracker/quality_control/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import BugReportForm, FeatureRequestForm
from .models import BugReport, FeatureRequest

from django.shortcuts import get_object_or_404
from django.views import View
from django.views.generic import DetailView
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView

from django.urls import reverse, reverse_lazy


def index(request):
    return render(request, 'quality_control/index.html')


def bug_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bugs_list.html', {'bugs_list': bugs})


def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'features': features})


def bug_detail(request, bug_id):
    bug = get_object_or_404(BugReport, id=bug_id)
    return render(request, 'quality_control/bugs_detail.html', {'bug': bug})


def feature_id_detail(request, feature_id):
    feature = get_object_or_404(FeatureRequest, id=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'feature': feature})


def create_bugreport(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bugs_list')
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_report_form.html', {'form': form})


def create_featurerequest(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_list')
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_request_form.html', {'form': form})


def update_bugreport(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bugs_detail', bug_id=bug_id)
    else:
        form = BugReportForm(instance=bug)
    return render(request, 'quality_control/bugs_update.html', {'form': form, 'bug': bug})


def update_featurerequest(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_detail', feature_id=feature_id)
    else:
        form = FeatureRequestForm(instance=feature)
    return render(request, 'quality_control/feature_update.html', {'form': form, 'feature': feature})


def delete_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    bug.delete()
    return redirect('quality_control:bugs_list')


def delete_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    feature.delete()
    return redirect('quality_control:feature_list')


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')


class BugsDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    template_name = 'quality_control/bugs_detail.html'


class FeaturesDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    template_name = 'quality_control/feature_detail.html'


class BugReportCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_form.html'
    success_url = reverse_lazy('quality_control:bugs_list')


class FeatureRequestCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_form.html'
    success_url = reverse_lazy('quality_control:feature_list')


class BugReportUpdateView(UpdateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bugs_update.html'
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bugs_detail')


class FeatureRequestUpdateView(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_update.html'
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:feature_detail')


class BugReportDeleteView(DeleteView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bugs_list')
    template_name = 'quality_control/bugs_confirm_delete.html'


class FeatureRequestDeleteView(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:feature_list')
    template_name = 'quality_control/feature_confirm_delete.html'

project_tracker/quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Создать новый bugreport</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bugs_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление bugreport</h1>
    <p>Вы уверены, что хотите удалить bugreport "{{ bugreport.id }}"?</p>

    <form action="{% url 'quality_control:delete_bug' bugreport.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bugs_detail' bugreport.id %}">Отмена</a>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bugs_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <!-- Ссылка для изменения проекта -->
    <p><a href="{% url 'quality_control:update_bugreport' bugreport.id %}">Изменить bug report</a></p>

    <!-- Ссылка удаления проекта -->
    <p><a href="{% url 'quality_control:delete_bug' bugreport.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот bug?');">Удалить bug</a></p>

    <h1>Детали бага {{bugreport.id}}</h1><h2>{{bugreport.title}}</h2><p>{{bugreport.description}}<p/>
    <p>Статус: {{bugreport.status}}</p>
    <p>Приоритет: {{bugreport.priority}}</p>
    <p>Cвязанный проект: {{bugreport.project}}</p>
    <p>Cвязаная задачи: {{bugreport.task}}</p>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bugs_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список bug report</h1><ul>

     <!-- Ссылка для добавления нового bug report -->
    <p><a href="{% url 'quality_control:create_bugreport' %}">Добавить новый bug report</a></p>

    {% for bug in bugs_list %}
        <li>{{bug.title}}<br/>Статус: {{bug.status}}<br/><a href="{% url 'quality_control:bugs_detail' bug.id %}">Детали бага {{bug.id}}</a></li>
    {% empty %}
            <li>В этом проекте пока нет багов.</li>
    {% endfor %}
    </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bugs_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение bug report: {{ bugreport.id }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса на улучшение</h1>
    <p>Вы уверены, что хотите удалить запроc на улучшение "{{ featurerequest.id }}"?</p>

    <form action="{% url 'quality_control:delete_feature' featurerequest.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_detail' featurerequest.id %}">Отмена</a>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <!-- Ссылка для изменения проекта -->
    <p><a href="{% url 'quality_control:update_featurerequest' featurerequest.id %}">Изменить запрос на улучшение</a></p>

    <!-- Ссылка удаления проекта -->
    <p><a href="{% url 'quality_control:delete_feature' featurerequest.id %}"onclick="return confirm('Вы уверены, что хотите удалить этот запрос на улучшение?');">Удалить запрос на улучшение</a></p>

    <h1>Детали бага {{featurerequest.id}}</h1><h2>{{featurerequest.title}}</h2><p>{{featurerequest.description}}<p/>
    <p>Статус: {{featurerequest.status}}</p>
    <p>Приоритет: {{featurerequest.priority}}</p>
    <p>Cвязанный проект: {{featurerequest.project}}</p>
    <p>Cвязаная задачи: {{featurerequest.task}}</p>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Cписок запросов на улучшение</h1><ul>

    <!-- Ссылка для добавления нового bug report -->
    <p><a href="{% url 'quality_control:create_featurerequest' %}">Добавить новый запрос на улучшение</a></p>

    {% for feature in features %}
        <li>{{feature.title}}<br/>Статус: {{feature.status}}<br/><a href="{% url 'quality_control:feature_detail' feature.id %}">Детали улучшения {{feature.id}}</a></li>
    {% empty %}
            <li>В этом проекте пока нет запросов.</li>
    {% endfor %}
    </ul>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Создать новый запрос</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение запроса на улучшение: {{ featurerequest.id }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Система контроля качества</h1>
    <a href="{% url 'quality_control:bugs_list' %}">Список всех багов</a><br/>
    <a href="{% url 'quality_control:feature_list' %}">Запросы на улучшение</a>
{% endblock %}
</html>